### ISSUE TITLE
Usage of Cose layout

### ISSUE THREAD

**Issue by neuhausi** [iVis-at-Bilkent/cose-base#12]
Is it possible to use the cose layout outside of Cytosape? Sorry if this is not the right forum to ask this question

**Comment by ugurdogrusoz** [comment]
@neuhausi First of all, let me clarify that this repo is for use and reuse in our other layout styles (e.g. cose-bilkent and fcose), not meant to be used alone. But for a sample use of it, within other JS libraries you may refer to fcose repository for instance. Alternatively, you can use [this service](https://github.com/iVis-at-Bilkent/syblars) that allows one to input a graph in formats such as JSON and graphml and get the results (coordinates) in JSON.

**Comment by neuhausi** [comment]
@ugurdogrusoz Thank you for the reply.  The only repo I found is for fcose is [this](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose) which also requires cytoscape. Is it possible to use it with D3 or CanvasXpress?

**Comment by ugurdogrusoz** [comment]
Yes, that's the correct repo for fcose. You basically have two choices at this point:
- Use syblars service pointed out earlier (in which case you might as well use fcose as it's an improved algorithm)
- Use cose-base as it is currently used in fcose

**Comment by neuhausi** [comment]
So just to be clear. It is not possible to use it with  D3 like cola.

**Comment by ugurdogrusoz** [comment]
You could use cose-base (which is independent of rendering library) with any library including D3. But it's not straightforward. An example usage is in fcose.

**Comment by neuhausi** [comment]
Ok. Thank you very much.
