### ISSUE TITLE
Tiling during incremental layout

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cose-base#7]
Currently, tiling operation during the incremental layout positions the tiled nodes in the root graph to a default/predefined position. Instead, it should preserve the old positions of the tiled nodes as much as possible. Using the average position of the nodes to be tiled can be considered for this purpose.

**Comment by hasanbalci** [comment]
I solved this issue with the commit 321477dc81246539f9c660dbb9b10edcf3f03878. I used the average of the center positions of the nodes to be tiled as the center position of the representative compound node. These compound nodes now start to the layout from these assigned positions instead of 0,0. This improves the incremental layout by preserving the positions of the tiled nodes as much as possible.

**Comment by ugurdogrusoz** [comment]
Perfect!
